### ISSUE TITLE
Hello, i'm looking for command to use this discover ... and can it work too for Rogue Squadron 2 and Rogue Squadron 3 on PS2 ?? games are from factor 5 too, and the same struture folder

### ISSUE THREAD

**Issue by Champszewonder** [dpethes/rerogue#1]

**Comment by dpethes** [comment]
Not sure what command you need. Which tool you're trying to use or what are you trying to achieve?
RS2 and 3 was for Gamecube, not PS2. The packed format for RS2 game data is similar, but slightly different. I made a modified data extractor that works for RS2. Other tools can't be used on RS2 data, since it's quite different. I don't have RS3 but I assume it's similar to RS2.

**Comment by Champszewonder** [comment]
my bad , yes, from Gamecube ... i can share you some data.dat files

i try to understand how it work for unpack the data.dat with your tool, because my previous unpacker, cannot find right extension of files, and i don't see how to convert 3D meshes.
i'm looking to extract, the TIE Hunter from it ... and some Carriers/Cruisers/Freighters

i hope with those files, you can increase the compatibility of your great tool
 link, of some levels.dat and data.dat of every games:
http://www.filedropper.com/gcrs2-3

**Comment by dpethes** [comment]
Move the rs_repack executable to the folder where _data.dat_ and _data.hdr_ are (it uses both of them) and run

```
rs_repack.exe u .\
```

The file extensions are underscore separated (eg. _explo2_IMGS_) and some files don't have any at all. And if by other unpacker you mean RogueDat, then it should give you more-or-less the same files as my rs_repack. 
The meshes are in a format that was custom made for the game and there's currently no convertor to other mesh formats. I made a simple viewer that works on most of the files, but that's all. However, a simple exporter to obj or other widely used 3d format should be rather easy to do.

I can upload the unpacker for RS2, but it doesn't work correctly for all cases yet. Also, the file formats are most probably custom made for the game again and no tools to use them exist, as far as I know.

**Comment by Champszewonder** [comment]
thks for the reply .. 
i will test this command tonight, and yes if youc an upload your tool for RS2, i will test it ...
now i must indentify which element are meshes or textures after the unpacking
i have see some elements with the name Tie Hunter, but not enough knowledge to identify format, if you viewer, can work on RS2/RS3 , it will be fantastic

**Comment by dpethes** [comment]
Try http://satd.sk/public/rs2dat_repack.zip to extract data.dat from RS2, crashes somewhere in the middle of that file though... If it finds compressed files, it decodes them (like player craft meshes).

**Comment by Choubi37** [comment]
hello

i have test it ..
what's wrong  into the sequence ?
no folder is create during the unpack

http://img15.hostingpics.net/pics/490861Capture.jpg
http://img11.hostingpics.net/pics/375231Capture2.jpg
