### ISSUE TITLE
Need help with hmp2obj

### ISSUE THREAD

**Issue by thanaclara** [dpethes/rerogue#2]
In you instructions on you blogsite it says you need to specify which map you are extracting. Do I specify it somewhere in the code project? If so where do I do that?

**Comment by dpethes** [comment]
As command line parameters: hmp2obj hmp text tex. "Hmp" is the heightmap file, "text" is the texture file, "tex" is the texture remapping index file (see blog for explanation of the texture files)

**Comment by thanaclara** [comment]
You mean like in cmd? Or is there a way to do this in lazarus?

**Comment by thanaclara** [comment]
This is a screenshot of the error it gives me when I do that.
![hmp2obj Error.](https://cloud.githubusercontent.com/assets/18415388/14536261/b6d2de52-022e-11e6-933a-60ab73092943.jpg)

**Comment by dpethes** [comment]
Aren't the TEX/TEXT file paths wrong? They are not in "lv_0" folder, at least not in my version. I added some path checks, it should help you find the wrong path.

**Comment by thanaclara** [comment]
Oh um well I copy and pasted those directly from your site. But now that I look at it in RogueDat I see what you mean. Still get the same error though when I adjust for this.

These were the new file paths I tried it with:

C:\Games\ROGUE\DATA\OUT\data\level\lv_0\hmp

C:\Games\ROGUE\DATA\OUT\data\level\lv_0_TEXT

C:\Games\ROGUE\DATA\OUT\data\level\lv_0_TEX

**Comment by thanaclara** [comment]
Actually I got it working, because you pointed out that I was looking in the wrong directory for TEX and TEXT I now was able to go into RogueDat and extract them correctly and use hmp2obj.exe on the extracted files instead of trying to do it in the .DAT file. I might suggest updating the misleading paths within the .DAT file for TEX and TEXT on your page. I genuinely thought I was supposed to point to the file contained within the .DAT file because I could totally see them in RogueDat but wasn't able to extract them until you pointed out I was looking in the wrong directory. I only mean to be helpful. I sincerely appreciate you helping me!

**Comment by dpethes** [comment]
Indeed, the path on the page is wrong. It doesn't work with the DAT file, as you figured out - it needs the data unpacked, though I use the dat_repack tool instead of RogueDat. I probably should make it work with the packed DAT file, it would be more comfortable.

**Comment by thanaclara** [comment]
It could potentially be helpful though it works like a charm now. Let me know if you want me to design a user friendly UI for it. I think that would open this sort of thing up to more people and grow the community. :)

**Comment by dpethes** [comment]
After putting some thought to it, I still think I'd invest my time into researching the map and 3d model format rather than working on a nice UI. But it's also true that just one (or none) parameter to run the programs would be way less confusing and easier to get started with.

**Comment by dpethes** [comment]
Created issue #3
