### ISSUE TITLE
Use DAT files directly in all tools

### ISSUE THREAD

**Issue by dpethes** [dpethes/rerogue#3]
The tools should be able to read their respective files without unpacking the DAT file. This would especially be useful for the map/terrain tools, which could accept just one parameter (level number) instead of three.

**Comment by thanaclara** [comment]
That is fantastic news!

Also, I'd hate to bother you but I was wondering if you had any advice on how to work with those SNG files? My end goal would be to convert them to MIDI.

**Comment by dpethes** [comment]
There's this project, but I think it works only for audio effects https://github.com/jackoalan/swrs_musyx . Otherwise, metroid used the same or similar version of musyx, it may be useful to look at it. I think there's a wiki somewhere about it.

**Comment by p4kistan** [comment]
Hey depethes, 

Is GitHub the best venue to track your progress? i.e is there a specific forum out there where RS3D editing (and your work in particular) is being discussed

**Comment by dpethes** [comment]
Hey, I don't present the results anywhere else at the moment, so github only. I'm at the point where I'm trying to read HOBs with multiple meshes properly. All HMT files work now, so with a lot of effort one could do some texturing mods.

**Comment by thanaclara** [comment]
@p4kistan you can now follow this project as well as a couple other tandem projects at reddit.com/r/StarWarsReRogue
