### ISSUE TITLE
Python bundle (un)pack; opkg files; craft animation/weapons config?

### ISSUE THREAD

**Issue by BenChampion** [dpethes/rerogue#5]
Hey - first off great project, very impressive work you've done so far!

I couldn't get the Rust version of the bundle unpacker to compile (I think the Rust io functionality has changed quite considerably in the intervening years). The format doesn't look too tricky, so I'm in the middle of writing a Python version. Interestingly, it looks like `BUNDLE.003` on my installation (from Steam) has a different format to the other `BUNDLE.00{0,1,2}` files. From looking in a hex editor it seems it maybe contains force-feedback and/or sound configuration.

Using the version of `model_viewer.exe` from your webpage, I noticed that there seems to be something differerent with the level data. A typical example is `data/level/lv_8/opkg_HOB`: if I turn on "points" under rendering options I can see other objects in the file (that make sense for the level), although we don't yet seem to be able to recover the faces. Typically the `opkg2_HOB` files appear empty.

Similarly, many of the objects seem to contain both their whole and destroyed versions. A particularly interesting example is `data/imp_stuff/atst_HOB`, where it looks like maybe the head shows up as "points" but at a much larger scale than the legs.

Maybe this is a clue to understanding the full HOB file format (although really I should try compiling the latest `model_viewer.exe`, I don't know if this is already figured out there!)

Finally, I've not come across any of the config that defines craft animations (brake flaps on the speeder, S-Foils on the X-Wing, maybe others). I haven't looked in the bundle files yet. Do you think that exists somewhere in the data or is it compiled directly into the code? Similarly, I've not seen the config that defines the weapons available on a craft and their graphics (red vs. green lasers etc.)

Ultimately my aim is to be able to play as different craft (e.g. maybe TIE Bomber on Y-Wing Levels, or T16 on other levels) or even fully custom models. Let's see how far we get!

(Sorry for the long issue, I can split this up if it makes more sense)

**Comment by dpethes** [comment]
Hi, we can replace the Rust version with the python one. The bundle format is described here: http://wiki.xentax.com/index.php/Rogue_Squadron_3D_000 . The files themselves are a bit of a mess, according to my old notes - these files are missing a section or not in correct format:
data\BUNDLE.000 - just the header section of BUNDLE.000 
BUNDLE.001 - just the header section of data\BUNDLE.001
BUNDLE.003 - not a bundle file

IIRC Star Wars : Behind The Magic interactive encyclopedia also used this format.

Yes, there are multiple models in opkg hob-s. The viewer displays them (or used to) on top of each other - I never figured out how are the models positioned on the map, nor their relative scale. Now I'm not sure if it reads the whole HOB or just a part of it.
I don't think there has been any development on the hob format for some years. There's a "hidden" feature in viewer, facegroup switching - press F and then left/right arrow to view specific vertex group - try on X-wing for example. I think the game is hardwired to operate on some specifically named groups to do the animations - there really aren't that many.

One issue is ok; if we figure out anything it'll most likely be related to HOB. Make a PR for the python bundle repacker if you feel it's ready (delete the rust one as part of PR), thank you.

**Comment by BenChampion** [comment]
> Hi, we can replace the Rust version with the python one. The bundle format is described here: http://wiki.xentax.com/index.php/Rogue_Squadron_3D_000 . The files themselves are a bit of a mess, according to my old notes - these files are missing a section or not in correct format:
> data\BUNDLE.000 - just the header section of BUNDLE.000
> BUNDLE.001 - just the header section of data\BUNDLE.001
> BUNDLE.003 - not a bundle file

Great! Sent [a pull request](https://github.com/dpethes/rerogue/pull/6). Thanks for the info on the files, I was a bit confused why those ones weren't working... (I wonder if those extra header-only files are there for a reason? Maybe so they can be read to pack the files in the right order every time? My attempt to pack the files in arbitrary order -- but still with proper headers -- didn't seem to work)

> Yes, there are multiple models in opkg hob-s. The viewer displays them (or used to) on top of each other - I never figured out how are the models positioned on the map, nor their relative scale.  Now I'm not sure if it reads the whole HOB or just a part of it.

Ah yes, I see you mentioned the multiple models on your webpage already, I had missed that. 

About positioning on the map: what do we know so far about the `dat` files in each `lv_X` subdirectory? I see these have object names that are also in the HOB files (e.g.  I see `v_ban_hi` in  `data\level\lv_0\dat` and also in for `data\level\lv_0\opkg_HOB` - which from the context is referring to Banthas). So I guess it refers just to a part of the HOB, seemingly by name. It looks like it's binding that mesh to an object instance name; it might also specify the location. I also see stuff like `TIE_Bomber_Spline_MAIN_0` which sounds less like an object and more like a flight path (?)

> I don't think there has been any development on the hob format for some years. There's a "hidden" feature in viewer, facegroup switching - press F and then left/right arrow to view specific vertex group - try on X-wing for example. I think the game is hardwired to operate on some specifically named groups to do the animations - there really aren't that many.

I was able to compile the latest `model_viewer` and try this feature - cool! Probably that's part of the reason why the models are not freely interchangeable.

I'll see if I can figure out anything more on the `HOB` (or `dat`) files. I'll start with the unknown fields in your spec, I guess!

**Comment by dpethes** [comment]
I have no notes about the DAT files, but I think you're right, it really looks like instance name + model name. I broke my RS instance somehow, so I'll have to switch to other pc to verify or fix my installation.

**Comment by BenChampion** [comment]
Closing this - will create further issues on specific topics.
